### POST request to upload file to test endpoint

POST http://{{env}}/api/printer-files/21/reload-thumbnail
Content-Type: application/json

{
 "filePath": "TEST-Shape-Box_0.4n_0.2mm_PLA_MINI_21m.gcode"
}

###
