nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.15.0.cjs
httpTimeout: 1000000

# Make the default explicit:
# Disable scripts since we don't want to run any postinstall scripts in this project
enableScripts: false