# https://fig.io/manual/pm2/install
---
- name: Install NVM, Node.js 20 (LTS), Yarn, FDM Monster on Ubuntu 22.04
  hosts: fdmm
  become: no
  vars_files:
    - vars/main.yml
  tasks:
    - name: Install nvm
      become: no
      shell: "curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v{{ nvm_version }}/install.sh | bash"
      args:
        executable: /bin/bash
        chdir: "{{ ansible_env.HOME }}"
        creates: "{{ ansible_env.HOME }}/.nvm/nvm.sh"

    - name: Set bash command
      set_fact:
        bash: "bash -ic"
        src_nvm: ". {{ ansible_env.HOME }}/.nvm/nvm.sh"

    - name: Install node
      become: no
      shell: "{{ bash }} 'nvm install {{ node_version }}'"
      args:
        executable: /bin/bash
        chdir: "{{ ansible_env.HOME }}"
        creates: "{{ ansible_env.HOME }}/.nvm/versions/{{ node_version }}"
      register: node_install_response
      changed_when: "'already installed' not in node_install_response.stderr"

    - name: "Set nvm used node version to {{ node_version }}"
      shell: "{{ bash }} 'nvm use {{ node_version }}'"
      register: nvm_use_response
      changed_when: nvm_use_response.rc != 0

    - name: "Install pm2 with yarn"
      shell: "{{ bash }} 'npm i -g add pm2'"

    - name: Ensure pm2 is not running
      command: "{{ bash }} 'pm2 kill'"

    - name: "Create /tmp/@fdm-monster as pm2 will fail without"
      file:
        path: "/tmp/@fdm-monster"
        state: directory
        owner: "{{ ansible_env.USER }}"
        group: "{{ ansible_env.USER }}"
        mode: "0755"

    - name: "Install @fdm-monster/server as pm2 module"
      shell: "{{ bash }} 'pm2 install @fdm-monster/server@{{fdmm_version}} -n fdmm'"

    - name: Set Node.js Full Version as a variable
      command: "{{ bash }} 'nvm current'"
      register: node_fullversion
      ignore_errors: true

    - name: Set PM2 to start on reboot
      become: yes
      command: "{{ bash }} 'env PATH=$PATH:/home/{{ ansible_user }}/.nvm/versions/node/{{ node_fullversion.stdout }}/bin pm2 startup {{ pm2_startup_type }} -u {{ ansible_user }} --hp /home/{{ ansible_user }}'"

    - name: Save PM2
      command: "{{ bash }} 'pm2 save'"

    # Future steps or possibilities
    # - name: "Make directory fdm-monster"
    #   file:
    #     path: "{{ ansible_env.HOME }}/.fdm-monster"
    #     state: directory
    #     owner: "{{ ansible_env.USER }}"
    #     group: "{{ ansible_env.USER }}"

    # - name: "Copy pm2 ecosystem file"
    #   copy:
    #     src: "./ecosystem.config.js"
    #     dest: "{{ ansible_env.HOME }}/.fdm-monster/ecosystem.config.js"
    #     owner: "{{ ansible_env.USER }}"
    #     group: "{{ ansible_env.USER }}"
    #     mode: "0644"

    # - name: "Install fdm-monster/cli@{{cli_version}} with yarn"
    #   shell: "{{ bash }} 'yarn global add @fdm-monster/cli@{{cli_version}}'"
