export class OctoprintSystemInfoDto {
  "browser.user_agent": string;
  "connectivity.connection_check": string;
  "connectivity.connection_ok": boolean;
  "connectivity.enabled": boolean;
  "connectivity.online": boolean;
  "connectivity.resolution_check": string;
  "connectivity.resolution_ok": boolean;
  "env.hardware.cores": number;
  "env.hardware.freq": number;
  "env.hardware.ram": number;
  "env.os.bits": number;
  "env.os.id": string;
  "env.os.platform": string;
  "env.plugins.pi_support.model": string;
  "env.plugins.pi_support.throttle_check_enabled": boolean;
  "env.plugins.pi_support.throttle_check_functional": boolean;
  "env.plugins.pi_support.throttle_state": string;
  "env.python.pip": string;
  "env.python.version": string;
  "env.python.virtualenv": boolean;
  "octoprint.last_safe_mode.date": string;
  "octoprint.last_safe_mode.reason": string;
  "octoprint.safe_mode": boolean;
  "octoprint.version": string;
  "printer.firmware": string;
  "systeminfo.generated": string;
  "systeminfo.generator": string;
}
