### POST request to export system configuration as YAML
POST http://localhost:4000/api/server/yaml-export
Content-Type: application/json

{
  "exportPrinters": true,
  "exportFloorGrid": true,
  "exportFloors": true,
  "exportTags": true,
  "exportSettings": true,
  "exportUsers": true,
  "printerComparisonStrategiesByPriority": ["name", "url", "id"],
  "floorComparisonStrategiesByPriority": "name"
}

###
