export const EVENT_TYPES = {
  ClientAuthed: "ClientAuthed",
  ClientClosed: "ClientClosed",
  ClientOpened: "ClientOpened",
  Connected: "Connected",
  Disconnecting: "Disconnecting",
  Disconnected: "Disconnected",
  Dwelling: "Dwell",
  Eject: "Eject",
  Error: "Error",
  EStop: "EStop",
  FileAdded: "FileAdded",
  FileDeselected: "FileDeselected",
  FileRemoved: "FileRemoved",
  FirmwareData: "FirmwareData",
  FolderAdded: "FolderAdded",
  FolderRemoved: "FolderRemoved",
  Home: "Home",
  MetadataAnalysisFinished: "MetadataAnalysisFinished",
  MetadataAnalysisStarted: "MetadataAnalysisStarted",
  MetadataStatisticsUpdated: "MetadataStatisticsUpdated",
  PositionUpdate: "PositionUpdate",
  PowerOff: "PowerOff",
  PowerOn: "PowerOn",
  PrintCancelled: "PrintCancelled",
  PrintCancelling: "PrintCancelling",
  PrintDone: "PrintDone",
  PrintFailed: "PrintFailed",
  PrintPaused: "PrintPaused",
  PrintResumed: "PrintResumed",
  PrintStarted: "PrintStarted",
  PrinterStateChanged: "PrinterStateChanged",
  TransferDone: "TransferDone",
  TransferStarted: "TransferStarted",
  UpdatedFiles: "UpdatedFiles",
  Upload: "Upload",
  UserLoggedIn: "UserLoggedIn",
  Waiting: "Waiting",
  ZChange: "ZChange",
} as const;

export const EVENT_TYPES_ARRAY = Object.values(EVENT_TYPES);

export type EventType = (typeof EVENT_TYPES_ARRAY)[number];
