const DITokens = {
  loggerFactory: "loggerFactory",
  httpClient: "httpClient",
  printerService: "printerService",
  printerGroupService: "printerGroupService",
  farmStatisticsService: "farmStatisticsService",
  serverSettingsService: "serverSettingsService",
  serverUpdateService: "serverUpdateService",
  githubApiService: "githubApiService",
  octoPrintApiService: "octoPrintApiService",
  filamentManagerPluginService: "filamentManagerPluginService",
  influxDbSetupService: "influxDbSetupService",
  influxDbFilamentService: "influxDbFilamentService",
  influxDbHistoryService: "influxDbHistoryService",
  influxDbPrinterStateService: "InfluxDbPrinterStateService",
  taskManagerService: "taskManagerService",
  printerFilesService: "printerFilesService",
  alertService: "alertService",
  scriptService: "scriptService",
  autoDiscoveryService: "autoDiscoveryService",
  historyService: "historyService",
  // Stores/states
  settingsStore: "settingsStore",
  printersStore: "printersStore",
  systemInfoStore: "systemInfoStore",
  filesStore: "filesStore",
  printerStateFactory: "printerStateFactory",
  printerState: "printerState",
  // Caches
  sortingFilteringCache: "sortingFilteringCache",
  heatMapCache: "heatMapCache",
  connectionLogsCache: "connectionLogsCache",
  jobsCache: "jobsCache",
  dashboardStatisticsCache: "dashboardCache",
  currentOperationsCache: "currentOperationsCache",
  fileCache: "fileCache",
  historyCache: "historyCache",
  filamentCache: "filamentCache",
  // Tasks
  printerSystemTask: "printerSystemTask",
  softwareUpdateTask: "softwareUpdateTask",
  printerSseTask: "printerSseTask",
  printerTestTask: "printerTestTask",
  systemCommandsService: "systemCommandsService",
  printerWebsocketTask: "printerWebsocketTask",
  printerFilesTask: "printerFilesTask"

};

module.exports = DITokens;
