module.exports = {
  testEnvironment: "node",
  testTimeout: 5000,
  modulePathIgnorePatterns: [
    "index.mjs",
    "migrate-mongo-config.js",
    ".eslintrc.js",
    "jest.config.js",
    "assets",
    "coverage",
    "docker",
    "file-storage",
    "node_modules",
    "logs",
    "views",
  ],
  globalSetup: "./test/setup-global.js",
  setupFilesAfterEnv: ["jest-27-expect-message", "./test/setup-after-env.js"],
  collectCoverageFrom: ["**/*.js"],
  coveragePathIgnorePatterns: ["node_modules", "test"],
  coverageReporters: ["clover", "json", "lcov", "text", "@lcov-viewer/istanbul-report"],
};
