/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export class OctoPrintSettingsDto {
  api?: {
    allowCrossOrigin?: boolean;
    key?: string;
  };
  appearance?: {
    closeModalsWithClick?: boolean;
    color?: string;
    colorIcon?: boolean;
    colorTransparent?: boolean;
    defaultLanguage?: string;
    fuzzyTimes?: boolean;
    name?: string;
    showFahrenheitAlso?: boolean;
    showInternalFilename?: boolean;
  };
  devel?: {
    pluginTimings?: boolean;
  };
  feature?: {
    autoUppercaseBlacklist?: string[];
    g90InfluencesExtruder?: boolean;
    keyboardControl?: boolean;
    modelSizeDetection?: boolean;
    pollWatched?: boolean;
    printCancelConfirmation?: boolean;
    printStartConfirmation?: boolean;
    sdSupport?: boolean;
    temperatureGraph?: boolean;
  };
  folder?: {
    logs?: string;
    timelapse?: string;
    timelapseTmp?: string;
    uploads?: string;
    watched?: string;
  };
  gcodeAnalysis?: {
    runAt?: string;
  };
  plugins?: {
    action_command_notification?: {
      enable?: boolean;
      enable_popups?: boolean;
    };
    action_command_prompt?: {
      command?: string;
      enable?: string;
      enable_emergency_sending?: boolean;
      enable_signal_support?: boolean;
    };
    announcements?: {
      channel_order?: string[];
      channels?: {
        _blog?: {
          description?: string;
          name?: string;
          priority?: number;
          read_until?: number;
          type?: string;
          url?: string;
        };
        _important?: {
          description?: string;
          name?: string;
          priority?: number;
          read_until?: number;
          type?: string;
          url?: string;
        };
        _octopi?: {
          description?: string;
          name?: string;
          priority?: number;
          read_until?: number;
          type?: string;
          url?: string;
        };
        _plugins?: {
          description?: string;
          name?: string;
          priority?: number;
          read_until?: number;
          type?: string;
          url?: string;
        };
        _releases?: {
          description?: string;
          name?: string;
          priority?: number;
          read_until?: number;
          type?: string;
          url?: string;
        };
      };
      display_limit?: number;
      enabled_channels?: string[];
      forced_channels?: string[];
      summary_limit?: number;
      ttl?: number;
    };
    backup?: {
      restore_unsupported?: boolean;
    };
    discovery?: {
      addresses?: any;
      httpPassword?: any;
      httpUsername?: any;
      interfaces?: any;
      model?: {
        description?: string;
        name?: string;
        number?: any;
        serial?: string;
        url?: string;
        vendor?: string;
        vendorUrl?: string;
      };
      pathPrefix?: any;
      publicHost?: any;
      publicPort?: any;
      upnpUuid?: string;
      zeroConf?: any[];
    };
    errortracking?: {
      enabled?: boolean;
      enabled_unreleased?: boolean;
      unique_id?: string;
      url_coreui?: string;
      url_server?: string;
    };
    firmware_check?: {
      ignore_infos?: boolean;
    };
    gcodeviewer?: {
      mobileSizeThreshold?: number;
      sizeThreshold?: number;
    };
    pi_support?: {
      ignore_unrecommended_model?: boolean;
      vcgencmd_throttle_check_command?: string;
      vcgencmd_throttle_check_enabled?: boolean;
    };
    pluginmanager?: {
      confirm_disable?: boolean;
      dependency_links?: boolean;
      hidden?: any[];
      ignore_throttled?: boolean;
      notices?: string;
      notices_ttl?: number;
      pip_args?: any;
      pip_force_user?: boolean;
      repository?: string;
      repository_ttl?: number;
    };
    softwareupdate?: {
      cache_ttl?: number;
      check_overlay_ttl?: number;
      check_overlay_url?: string;
      credentials?: {
        [k: string]: any;
      };
      ignore_throttled?: boolean;
      minimum_free_storage?: number;
      notify_users?: boolean;
      octoprint_branch_mappings?: {
        branch: string;
        commitish: string[];
        name: string;
      }[];
      octoprint_checkout_folder?: any;
      octoprint_method?: string;
      octoprint_pip_target?: string;
      octoprint_release_channel?: string;
      octoprint_tracked_branch?: any;
      octoprint_type?: string;
      pip_command?: any;
      pip_enable_check?: boolean;
    };
    tracking?: {
      enabled?: boolean;
      events?: {
        commerror?: boolean;
        plugin?: boolean;
        pong?: boolean;
        printer?: boolean;
        printer_safety_check?: boolean;
        printjob?: boolean;
        slicing?: boolean;
        startup?: boolean;
        throttled?: boolean;
        update?: boolean;
      };
      ping?: any;
      pong?: number;
      server?: any;
      unique_id?: string;
    };
    virtual_printer?: {
      ambientTemperature?: number;
      brokenM29?: boolean;
      brokenResend?: boolean;
      busyInterval?: number;
      capabilities?: {
        AUTOREPORT_SD_STATUS?: boolean;
        AUTOREPORT_TEMP?: boolean;
        EMERGENCY_PARSER?: boolean;
      };
      commandBuffer?: number;
      echoOnM117?: boolean;
      enable_eeprom?: boolean;
      enabled?: boolean;
      errors?: {
        checksum_mismatch?: string;
        checksum_missing?: string;
        command_unknown?: string;
        lineno_mismatch?: string;
        lineno_missing?: string;
        maxtemp?: string;
        mintemp?: string;
      };
      firmwareName?: string;
      forceChecksum?: boolean;
      hasBed?: boolean;
      hasChamber?: boolean;
      includeCurrentToolInTemps?: boolean;
      includeFilenameInOpened?: boolean;
      klipperTemperatureReporting?: boolean;
      m105NoTargetFormatString?: string;
      m105TargetFormatString?: string;
      m114FormatString?: string;
      m115FormatString?: string;
      m115ReportCapabilities?: boolean;
      numExtruders?: number;
      okAfterResend?: boolean;
      okBeforeCommandOutput?: boolean;
      okFormatString?: string;
      pinnedExtruders?: any;
      preparedOks?: any[];
      repetierStyleTargetTemperature?: boolean;
      reprapfwM114?: boolean;
      resend_ratio?: number;
      resetLines?: string[];
      rxBuffer?: number;
      sdFiles?: {
        longname?: boolean;
        size?: boolean;
      };
      sendBusy?: boolean;
      sendWait?: boolean;
      sharedNozzle?: boolean;
      simulateReset?: boolean;
      smoothieTemperatureReporting?: boolean;
      supportF?: boolean;
      supportM112?: boolean;
      support_M503?: boolean;
      throttle?: number;
      waitInterval?: number;
    };
  };
  printer?: {
    defaultExtrusionLength?: number;
  };
  scripts?: {
    gcode?: {
      afterPrintCancelled?: string;
      "snippets/disable_bed"?: string;
      "snippets/disable_hotends"?: string;
    };
  };
  serial?: {
    abortHeatupOnCancel?: boolean;
    ackMax?: number;
    additionalBaudrates?: any[];
    additionalPorts?: any[];
    alwaysSendChecksum?: boolean;
    autoconnect?: boolean;
    baudrate?: number;
    baudrateOptions?: number[];
    blacklistedBaudrates?: any[];
    blacklistedPorts?: any[];
    blockWhileDwelling?: boolean;
    blockedCommands?: string[];
    capAutoreportSdStatus?: boolean;
    capAutoreportTemp?: boolean;
    capBusyProtocol?: boolean;
    capEmergencyParser?: boolean;
    checksumRequiringCommands?: string[];
    disableSdPrintingDetection?: boolean;
    disconnectOnErrors?: boolean;
    emergencyCommands?: string[];
    exclusive?: boolean;
    externalHeatupDetection?: boolean;
    firmwareDetection?: boolean;
    helloCommand?: string;
    ignoreErrorsFromFirmware?: boolean;
    ignoreIdenticalResends?: boolean;
    log?: boolean;
    logPositionOnCancel?: boolean;
    logPositionOnPause?: boolean;
    longRunningCommands?: string[];
    maxTimeoutsIdle?: number;
    maxTimeoutsLong?: number;
    maxTimeoutsPrinting?: number;
    neverSendChecksum?: boolean;
    notifySuppressedCommands?: string;
    pausingCommands?: string[];
    port?: number;
    portOptions?: any[];
    repetierTargetTemp?: boolean;
    resendRatioStart?: number;
    resendRatioThreshold?: number;
    sanityCheckTools?: boolean;
    sdAlwaysAvailable?: boolean;
    sdRelativePath?: boolean;
    sendM112OnError?: boolean;
    supportResendsWithoutOk?: string;
    swallowOkAfterResend?: boolean;
    timeoutBaudrateDetectionPause?: number;
    timeoutCommunication?: number;
    timeoutCommunicationBusy?: number;
    timeoutConnection?: number;
    timeoutDetectionConsecutive?: number;
    timeoutDetectionFirst?: number;
    timeoutPositionLogWait?: number;
    timeoutSdStatus?: number;
    timeoutSdStatusAutoreport?: number;
    timeoutTemperature?: number;
    timeoutTemperatureAutoreport?: number;
    timeoutTemperatureTargetSet?: number;
    triggerOkForM29?: boolean;
    useParityWorkaround?: string;
    waitForStart?: boolean;
  };
  server?: {
    allowFraming?: boolean;
    commands?: {
      serverRestartCommand?: string;
      systemRestartCommand?: string;
      systemShutdownCommand?: string;
    };
    diskspace?: {
      critical?: number;
      warning?: number;
    };
    onlineCheck?: {
      enabled?: boolean;
      host?: string;
      interval?: number;
      name?: string;
      port?: number;
    };
    pluginBlacklist?: {
      enabled?: boolean;
      ttl?: number;
      url?: string;
    };
  };
  system?: {
    actions?: any[];
    events?: any;
  };
  temperature?: {
    cutoff?: number;
    profiles: any[];
    //   Array<{
    //   bed: number;
    //   chamber: any;
    //   extruder: number;
    //   name: string;
    // }>;
    sendAutomatically?: boolean;
    sendAutomaticallyAfter?: number;
  };
  terminalFilters?: any[];
  //   {
  //   name: string;
  //   regex: string;
  // }[];
  webcam?: {
    bitrate?: string;
    ffmpegPath?: string;
    ffmpegThreads?: number;
    ffmpegVideoCodec?: string;
    flipH?: boolean;
    flipV?: boolean;
    rotate90?: boolean;
    snapshotSslValidation?: boolean;
    snapshotTimeout?: number;
    snapshotUrl?: string;
    streamRatio?: string;
    streamTimeout?: number;
    streamUrl?: string;
    timelapseEnabled?: boolean;
    watermark?: boolean;
    webcamEnabled?: boolean;
  };
}
