import type { PrinterObjectDto } from "@/services/moonraker/dto/objects/printer-object.dto";
import type { PauseResumeDto } from "@/services/moonraker/dto/objects/pause-resume.dto";
import type { GcodeDto } from "@/services/moonraker/dto/objects/gcode.dto";
import type { BedMeshDto } from "@/services/moonraker/dto/objects/bed-mesh.dto";
import type { ConfigfileDto } from "@/services/moonraker/dto/objects/configfile.dto";
import type { FilamentSwitchSensorDto } from "@/services/moonraker/dto/objects/filament-switch-sensor.dto";
import type { FilamentMotionSensorDto } from "@/services/moonraker/dto/objects/filament-motion-sensor.dto";
import type { DisplayStatusDto } from "@/services/moonraker/dto/objects/display-status.dto";
import type { GcodeMoveDto } from "@/services/moonraker/dto/objects/gcode-move.dto";
import type { HeaterBedDto } from "@/services/moonraker/dto/objects/heater-bed.dto";
import type { HeatersDto } from "@/services/moonraker/dto/objects/heaters.dto";
import type { IdleTimeoutDto } from "@/services/moonraker/dto/objects/idle-timeout.dto";
import type { McuDto } from "@/services/moonraker/dto/objects/mcu.dto";
import type { OutputPinDto } from "@/services/moonraker/dto/objects/output-pin.dto";
import type { TemperatureFanDto } from "@/services/moonraker/dto/objects/temperature-fan.dto";
import type { ToolheadDto } from "@/services/moonraker/dto/objects/toolhead.dto";
import type { VirtualSdcardDto } from "@/services/moonraker/dto/objects/virtual-sdcard.dto";
import type { WebhooksDto } from "@/services/moonraker/dto/objects/webhooks.dto";
import type { ExtruderDto } from "@/services/moonraker/dto/objects/extruder.dto";
import type { FanDto } from "@/services/moonraker/dto/objects/fan.dto";
import type { PrintStatsDto } from "@/services/moonraker/dto/objects/print-stats.dto";
import type { StepperEnableDto } from "@/services/moonraker/dto/objects/stepper-enable.dto";
import type { MotionReportDto } from "@/services/moonraker/dto/objects/motion-report.dto";
import type { SystemStatsDto } from "@/services/moonraker/dto/objects/system-stats.dto";

export type BedMeshObject = PrinterObjectDto<"bed_mesh", BedMeshDto>;
export type ConfigFileObject = PrinterObjectDto<"config_file", ConfigfileDto>;
export type DisplayStatusObject = PrinterObjectDto<"display_status", DisplayStatusDto>;
export type ExtruderObject = PrinterObjectDto<"extruder", ExtruderDto>;
export type FanObject = PrinterObjectDto<"fan", FanDto>;
export type FilamentSwitchSensorObject = PrinterObjectDto<"filament_switch_sensor", FilamentSwitchSensorDto>;
export type FilamentMotionSensorObject = PrinterObjectDto<"filament_motion_sensor", FilamentMotionSensorDto>;
export type GcodeObject = PrinterObjectDto<"gcode", GcodeDto>;
export type GcodeMacroObject = PrinterObjectDto<"gcode_macro", {}>;
export type GcodeMoveObject = PrinterObjectDto<"gcode_move", GcodeMoveDto>;
export type HeaterBedObject = PrinterObjectDto<"heater_bed", HeaterBedDto>;
export type HeatersObject = PrinterObjectDto<"heaters", HeatersDto>;
export type IdleTimeoutObject = PrinterObjectDto<"idle_timeout", IdleTimeoutDto>;
export type McuObject = PrinterObjectDto<"mcu", McuDto>;
export type MotionReportObject = PrinterObjectDto<"motion_report", MotionReportDto>;
export type OutputPinObject = PrinterObjectDto<"output_pin", OutputPinDto>;
export type PauseResumeObject = PrinterObjectDto<"pause_resume", PauseResumeDto>;
export type PrintStatsObject = PrinterObjectDto<"print_stats", PrintStatsDto>;
export type StepperEnableObject = PrinterObjectDto<"stepper_enable", StepperEnableDto>;
export type SystemStatsObject = PrinterObjectDto<"system_stats", SystemStatsDto>;
export type TemperatureFanObject = PrinterObjectDto<"temperature_fan", TemperatureFanDto>;
export type ToolheadObject = PrinterObjectDto<"toolhead", ToolheadDto>;
export type VirtualSdCardObject = PrinterObjectDto<"virtual_sdcard", VirtualSdcardDto>;
export type WebhooksObject = PrinterObjectDto<"webhooks", WebhooksDto>;
// export type Object = PrinterObjectDto<"", Dto>;
