### POST request to upload file to test endpoint

POST http://{{env}}/api/printer-files/1/reload-thumbnail
Content-Type: application/json

{
 "filePath": "Clay Golem Updated_0.05mm_PLA_MK3S_7h40m.gcode"
}

###
