export const POSTGRES_DATABASE_URL = "POSTGRES_DATABASE_URL";
export const TYPEORM_DATABASE = "TYPEORM_DATABASE";
export const TYPEORM_USERNAME = "TYPEORM_USERNAME";
export const TYPEORM_PASSWORD = "TYPEORM_PASSWORD";
