import os from "node:os";
import fs from "node:fs";
import path from "node:path";
import { GCodeParser } from "@/utils/parsers/gcode.parser";

// Larger than the parser's ~25KB footer window, to isolate header-only parsing.
const FOOTER_PAD = "G1 X1 Y1 E1 ; move\n".repeat(2000);

describe("GCodeParser routing token", () => {
  const parser = new GCodeParser();
  const tmpFiles: string[] = [];
  let fileSeq = 0;

  function writeGcode(name: string, content: string): string {
    const filePath = path.join(os.tmpdir(), `fdmm-gcode-${process.pid}-${++fileSeq}-${name}`);
    fs.writeFileSync(filePath, content);
    tmpFiles.push(filePath);
    return filePath;
  }

  afterAll(() => {
    for (const f of tmpFiles) {
      try {
        fs.unlinkSync(f);
      } catch {
        /* ignore */
      }
    }
  });

  it("parses the fdmm_target token from a PrusaSlicer-style comment", async () => {
    const file = writeGcode("prusa.gcode", "; generated by PrusaSlicer 2.7.0\n; fdmm_target = prusa-mini\nG28\n");
    const { normalized } = await parser.parse(file);
    expect(normalized.routingTarget).toBe("prusa-mini");
  });

  it("parses the fdmm_target token from a Cura-style comment", async () => {
    const file = writeGcode("cura.gcode", ";FLAVOR:Marlin\n;FDMM_TARGET:voron-350\nG28\n");
    const { normalized } = await parser.parse(file);
    expect(normalized.routingTarget).toBe("voron-350");
  });

  it("returns null routingTarget when no token is present", async () => {
    const file = writeGcode("none.gcode", "; generated by PrusaSlicer 2.7.0\nG28\nG1 X10\n");
    const { normalized } = await parser.parse(file);
    expect(normalized.routingTarget).toBeNull();
  });

  it("reads fdmm_target_printer as an explicit printer target", async () => {
    const file = writeGcode(
      "explicit-printer.gcode",
      "; generated by PrusaSlicer 2.7.0\n; fdmm_target_printer = voron-1\nG28\n",
    );
    const { normalized } = await parser.parse(file);
    expect(normalized.routingTarget).toBe("voron-1");
    expect(normalized.routingTargetKind).toBe("printer");
  });

  it("reads fdmm_target_tag as an explicit tag target", async () => {
    const file = writeGcode(
      "explicit-tag.gcode",
      "; generated by PrusaSlicer 2.7.0\n; fdmm_target_tag = prusa-fleet\nG28\n",
    );
    const { normalized } = await parser.parse(file);
    expect(normalized.routingTarget).toBe("prusa-fleet");
    expect(normalized.routingTargetKind).toBe("tag");
  });

  it("leaves routingTargetKind null for the bare fdmm_target token", async () => {
    const file = writeGcode("bare-kind.gcode", "; generated by PrusaSlicer 2.7.0\n; fdmm_target = prusa-mini\nG28\n");
    const { normalized } = await parser.parse(file);
    expect(normalized.routingTargetKind).toBeNull();
  });

  it("finds the routing token after a thumbnail block larger than the metadata line budget", async () => {
    const thumbnailBody = Array.from({ length: 800 }, () => "; QUJDQUJDQUJDQUJDQUJDQUJDQUJDQUJDQUJD").join("\n");
    const content =
      "; generated by PrusaSlicer 2.7.0\n" +
      "; thumbnail begin 320x240 123456\n" +
      thumbnailBody +
      "\n; thumbnail end\n" +
      "; fdmm_target = prusa-mk4\n" +
      FOOTER_PAD;
    const file = writeGcode("thumbnail.gcode", content);
    const { normalized } = await parser.parse(file);
    expect(normalized.routingTarget).toBe("prusa-mk4");
  });

  it("does not ingest thumbnail base64 lines as metadata keys", async () => {
    const pollutingKey = "iVBORw0KGgoAAAANSUhEUg";
    const thumbnailBody = Array.from({ length: 600 }, () => `; ${pollutingKey}==`).join("\n");
    const content =
      "; thumbnail begin 16x16 999\n" + thumbnailBody + "\n; thumbnail end\n" + "; layer_height = 0.2\n" + FOOTER_PAD;
    const file = writeGcode("nopollution.gcode", content);
    const { raw } = await parser.parse(file);
    expect(Object.keys(raw.metadata)).not.toContain(pollutingKey.toLowerCase());
    expect(raw.metadata.layer_height).toBe("0.2");
  });
});
